name: Scircumstances
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: SCIRCUMSTANCES
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#000000'
    - '#000000'
    - '#ffffff'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
