name: Scircumstances
favicon: null
layout_spectrum: 0.3972658119164407
typography_spectrum: 0.5790764864068478
title: SCIRCUMSTANCES
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#000000'
    - '#000000'
    - '#ffffff'
  brandStrength: 0.5
  lightness: 0.48590471781790257
  saturation: 0.8500568640884012
  rhythmicContrast: 0.6167066360358149
purpose: []
